---
particleCount: 200 # Change as needed
smoothRadius: 0.35
targetDensity: 55
pressureMultiplier: 150
nearPressureMultiplier: 10
viscosityMultiplier: 0.06
boundaryMultipler: 50000.0
gravityAccValue: 25
dataScale: 0.01
rangeForceScale: 75
rangeForceRadius: 2.0

startPoint:
  - 4
  - 1
stride: 0.1
maxWidth: 4
randomize: yes # Change as needed

windowSize:
  - 400 # Change as needed
  - 400 # Change as needed